title = "PSICE"
baseurl = "http://www.psice.psu.edu/"
languageCode = "en-us"
theme = "ghostwriter"
pluralizelisttitles = false
canonifyURLs = true

[Params]
    intro = true
    headline = "Ice and Climate (PSICE)"
    twitter="//twitter.com/psice280"
    gitlab="http://git.psu.edu/psice"
    github="http://github.com/sanandak"
    email="psice@psu.edu"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "/pubs/"
    weight = 4

[[menu.main]]
    name = "People"
    url = "/people/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6


[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 7

