version: '2'

services:
  drupal:
    build: .
    ports:
      - "8080:80"
      - "22"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: drupal
      MYSQL_USER: rpal_drupal
      MYSQL_PASSWORD
    volumes:
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
