# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 21 Feb 2016 19:14:04 +0000
*               @ALL          0
*               @user         8
