<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: avolkov
 * Date: Sun, 31 Jul 2016 14:24:15 -0400
 */

$conf['title'] = 'RPAL Internal Wiki';
$conf['start'] = 'root';
$conf['template'] = 'bootstrap3-edited';
$conf['license'] = '0';
$conf['basedir'] = '/wiki/';
$conf['baseurl'] = 'https://rpal.cs.cornell.edu';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['remoteuser'] = '';
$conf['htmlok'] = 1;
$conf['target']['interwiki'] = '_tab';
$conf['target']['extern'] = '_tab';
$conf['jpg_quality'] = 100;
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['proxy']['user'] = 'rpal_admin';
$conf['proxy']['pass'] = '<b>QUlCT1NtdWdnbGVy';
$conf['plugin']['gallery']['options'] = 'cache,lightbox,showname,showtitle';
$conf['plugin']['404manager']['ActionReaderSecond'] = 'GoToBestNamespace';
$conf['plugin']['404manager']['ActionReaderThird'] = 'GoToSearchEngine';
$conf['tpl']['bootstrap3-edited']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3-edited']['bootswatchTheme'] = 'flatly';
$conf['tpl']['bootstrap3-edited']['hideInThemeSwitcher'] = 'cerulean,cosmo,cyborg,paper,readable,slate,spacelab,superhero,yeti';
$conf['tpl']['bootstrap3-edited']['useLocalBootswatch'] = 0;
$conf['tpl']['bootstrap3-edited']['rightSidebar'] = '';
$conf['tpl']['bootstrap3-edited']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3-edited']['showTools'] = 'logged';
$conf['tpl']['bootstrap3-edited']['showSearchForm'] = 'logged';
$conf['tpl']['bootstrap3-edited']['schemaOrgType'] = 'TechArticle';
$conf['tpl']['bootstrap3-edited']['fluidContainerBtn'] = 1;
$conf['tpl']['bootstrap3-edited']['showBadges'] = 0;

// end auto-generated content
