#+DATE: 2017-07-16T08:00:00-04:00
#+TITLE: GMT files
#+DESCRIPTION: GMT files and scripts for Antarctica

The outline of the major ice shelves in Antarctica is missing from the
[[http://gmt.soest.hawaii.edu][GMT]] datasets.  I have included them and made them available in
[[add.tar.gz]] and [[greenland.dat.gz]]. 



For example, here is figure showing the Antarctic and Greenland ice
sheets (the GMT ~bash~ script to generate this figure is
[[./2poles.gmt][2poles.gmt here]].
{{< pdf "2poles.pdf" >}}

#+BEGIN_SRC bash
# ... some set up not shown

# draw the world 
pscoast -R0/360/-90/90 -JG-75/41/4.5i -B45/30 -Dc -A10000 \
    -G100/100/100 -X7c -Y10c -K -O >>$out
gunzip -c greenland.dat.gz | \
    psxy  -JG -R -M -G0/100/240 -K -O >>$out
#+END_SRC

GMT uses a terse set of command line flags.  In this case, we have:
  - ~-R0/360/-90/90~, which sets the /region/ to the whole globe
  - ~-JG-75/41/4.5i~ which sets the projection to /Azimuthal Orthographic/ with a projection center of 75W, 41N (approximately in Pennsylvania)and the width of the map is 4.5 inches.
  - ~-B45/30~ sets the drawing of gridlines to every 45 degrees in longitude, and every 30 degrees in latitude
  - ~-Dc~ says to only draw /coarse/ features
  - ~-A10000~ says to limit water features to those larger than 10,000 km square
  - ~-G~ specifies the color as gray
  - and the ~-X~ and ~-Y~ flags offset the map (units are 'c'=cm and 'i'=inches). In GMT, the origin is at the bottom left of the page, and the positive x- and y-axes are to the right and upwards, respectively.

The 2nd line uncompresses ~greenland.dat.gz~ and draws that outline in blue (using the same ~-R~ and ~-G~ parameters as before---if you give bare options, GMT will use the the most recent settings...).

#+BEGIN_SRC bash
#... draw the southern hemisphere and Antarctica in gray
pscoast -R0/360/-90/90 -JG-75/-41/4.5i -B45/30 -Dc \ 
    -A10000 -G100/100/100 -X-5c -Y-8c -K -O >>$out
# ... and add my outline on top in blue
gunzip -c ADDant.txt.gz | psxy -JG -R -M \
  -G0/100/240 -K -O >> $out
#+END_SRC

The GMT default Antarctic outline (drawn by the first command)
includes the ice shelves.  Here I use a projection center with the
same longitude, but with a latitude of /-41S/ (in the eastern Pacific
off the coast of S. America...).

The 2nd line uncompresses my outline (which excludes the
Ross, Filchner-Ronne, Amery, and Larsen ice shelves) and draws that over
the first outline.  

Note that the offset of this map is /relative/ to the previous drawing
location (which was, if you recall, 7c/10c from the origin at the
bottom left).  Thus the negative offsets moves the 2nd globe down and
to the left.  

